### ISSUE TITLE
Review/polish pages added in bulk

### ISSUE THREAD

**Issue by jholdstock** [jholdstock/dcrdevdocs#6]
#3 added a bunch of new pages to dcrdevdocs. These need to be individually reviewed, polished and/or Decred-ified.

Done:
- [x] `core-blockchain-concepts/blockchain.md`
- [x] `core-blockchain-concepts/hard-fork-voting-and-consensus-rule-changes.md`
- [x] `core-blockchain-concepts/transactions/transactions.md`
- [x] `core-blockchain-concepts/contracts.md`
- [x] `core-blockchain-concepts/transaction-data.md` (#25)
- [x] `protocol-p2p-network/blocks-first.md`
- [x] `protocol-p2p-network/headers-first.md`
- [x] `protocol-p2p-network/initial-block-download.md`
- [x] `protocol-p2p-network/orphan-blocks.md`
- [x] `protocol-p2p-network/transaction-broadcasting.md`
- [x] `protocol-p2p-network/memory-pool.md` (#26)
- [x] `protocol-p2p-network/peer-discovery.md` (#12)
- [x] `environments/mainnet.md`

In progress:
- [ ] `core-blockchain-concepts/merkle-root-construction.md` (#38)

Removed by #43:
- [ ] `core-blockchain-concepts/compact-filters-for-spv.md`
- [ ] `core-blockchain-concepts/fork-detection.md`
- [ ] `core-blockchain-concepts/lottery-selection-semantics.md`
- [ ] `core-blockchain-concepts/proof-of-work.md`
- [ ] `transactions/opcodes.md`
- [ ] `protocol-p2p-network/block-broadcasting.md`
- [ ] `protocol-p2p-network/connecting-to-peers.md`
- [ ] `protocol-p2p-network/misbehaving-nodes.md`
